name: Go
on: [push]

jobs:
  infra:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
    #      - uses: actions/checkout@v4
    #      - uses: actions/setup-go@v3
    #        with:
    #          go-version: 'stable'
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::613594639814:role/url-shortener-web-service
        aws-region: us-east-1
    - run: env